"""Provide safe, provider-neutral language-model generation for Phase 8 prompts."""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
import time
import urllib.error
import urllib.request
from collections import Counter
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from statistics import mean, median
from typing import Any, Final, Protocol, Sequence


DEFAULT_PROVIDER: Final = "offline"
DEFAULT_TIMEOUT_SECONDS: Final = 60.0
DEFAULT_MAX_OUTPUT_TOKENS: Final = 500
DEFAULT_RETRIES: Final = 2
SUPPORTED_PROVIDERS: Final = {"offline", "openai", "gemini", "anthropic", "ollama"}
TRANSIENT_STATUS_CODES: Final = {408, 409, 429, 500, 502, 503, 504}
CITATION_PATTERN: Final = re.compile(r"\[S\d+\]")


@dataclass(frozen=True)
class ClientConfig:
    """Validated provider, model, timeout, retry, and output settings."""

    provider: str = DEFAULT_PROVIDER
    model: str = "offline-grounded-v1"
    timeout_seconds: float = DEFAULT_TIMEOUT_SECONDS
    max_output_tokens: int = DEFAULT_MAX_OUTPUT_TOKENS
    retries: int = DEFAULT_RETRIES
    base_url: str | None = None

    def __post_init__(self) -> None:
        if self.provider not in SUPPORTED_PROVIDERS:
            raise ValueError(f"Unsupported provider: {self.provider}")
        if not self.model.strip():
            raise ValueError("Model name must not be empty.")
        if self.timeout_seconds <= 0:
            raise ValueError("Timeout must be positive.")
        if self.max_output_tokens < 32:
            raise ValueError("max_output_tokens must be at least 32.")
        if self.retries < 0:
            raise ValueError("retries must not be negative.")


@dataclass(frozen=True)
class LLMResponse:
    """Provider-neutral result returned to the Phase 10 RAG chain."""

    prompt_id: str
    provider: str
    model: str
    mode: str
    text: str
    citations: list[str]
    finish_reason: str
    latency_ms: float
    input_tokens: int | None
    output_tokens: int | None
    request_id: str | None
    safety_labels: list[str]


@dataclass(frozen=True)
class BatchResult:
    """Artifacts and counts generated by one LLM batch run."""

    responses_path: Path
    report_path: Path
    audit_path: Path
    failed_path: Path
    latency_plot_path: Path
    length_plot_path: Path
    input_prompts: int
    responses_created: int
    failed_responses: int


class Provider(Protocol):
    """Minimal provider contract used by the LLM client."""

    name: str

    def generate(self, bundle: dict[str, Any], config: ClientConfig) -> LLMResponse:
        """Generate one provider-neutral response."""


def default_project_root() -> Path:
    """Return the project root based on this module's location."""
    return Path(__file__).resolve().parents[1]


def load_env_file(path: Path) -> dict[str, str]:
    """Read simple KEY=VALUE settings without requiring python-dotenv."""
    values: dict[str, str] = {}
    if not path.is_file():
        return values
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def environment(project_root: Path) -> dict[str, str]:
    """Combine local .env values with process variables; process values win."""
    values = load_env_file(project_root / ".env")
    values.update({key: value for key, value in os.environ.items() if value})
    return values


def load_prompt_bundles(path: Path) -> list[dict[str, Any]]:
    """Load and validate the Phase 8 prompt bundle contract."""
    if not path.is_file():
        raise FileNotFoundError(f"Prompt bundles do not exist: {path}")
    payload = json.loads(path.read_text(encoding="utf-8"))
    required = {
        "prompt_id", "mode", "question", "system_prompt", "user_prompt",
        "sources", "safety_labels", "estimated_prompt_tokens",
    }
    if not isinstance(payload, list):
        raise ValueError("Prompt bundles must be a JSON list.")
    for number, bundle in enumerate(payload, start=1):
        if not isinstance(bundle, dict) or not required.issubset(bundle):
            raise ValueError(f"Prompt bundle {number} is invalid.")
    return payload


def config_from_environment(values: dict[str, str], provider: str | None = None) -> ClientConfig:
    """Build configuration with provider-specific model and base URL defaults."""
    selected = (provider or values.get("LLM_PROVIDER") or DEFAULT_PROVIDER).casefold()
    model_defaults = {
        "offline": "offline-grounded-v1",
        "openai": values.get("OPENAI_MODEL") or values.get("MODEL_NAME") or "",
        "gemini": values.get("GEMINI_MODEL") or "",
        "anthropic": values.get("ANTHROPIC_MODEL") or "",
        "ollama": values.get("OLLAMA_MODEL") or "",
    }
    base_defaults = {
        "openai": "https://api.openai.com/v1/responses",
        "gemini": "https://generativelanguage.googleapis.com/v1beta",
        "anthropic": "https://api.anthropic.com/v1/messages",
        "ollama": "http://localhost:11434/api/chat",
    }
    return ClientConfig(
        provider=selected,
        model=model_defaults.get(selected, ""),
        timeout_seconds=float(values.get("LLM_TIMEOUT_SECONDS", DEFAULT_TIMEOUT_SECONDS)),
        max_output_tokens=int(values.get("LLM_MAX_OUTPUT_TOKENS", DEFAULT_MAX_OUTPUT_TOKENS)),
        retries=int(values.get("LLM_RETRIES", DEFAULT_RETRIES)),
        base_url=values.get(f"{selected.upper()}_BASE_URL") or base_defaults.get(selected),
    )


def source_answer(source_text: str) -> str:
    """Extract a concise answer field or readable source excerpt."""
    match = re.search(r"(?:^|\|)\s*answer:\s*(.*?)(?:\s*\|\s*[a-z_]+:|$)", source_text, re.I)
    if match:
        return match.group(1).strip()
    compact = " ".join(source_text.split())
    sentences = re.split(r"(?<=[.!?])\s+", compact)
    return " ".join(sentences[:2])[:700].strip()


class OfflineProvider:
    """Deterministic provider for free, private, reproducible validation."""

    name = "offline"

    def generate(self, bundle: dict[str, Any], config: ClientConfig) -> LLMResponse:
        start = time.perf_counter()
        mode = str(bundle["mode"])
        sources = list(bundle.get("sources", []))
        if mode == "emergency":
            text = (
                "Contact local emergency services immediately or go to the nearest "
                "emergency department. I cannot diagnose the cause of your symptoms."
            )
        elif mode == "unsafe_medical_advice":
            text = (
                "I cannot diagnose a condition, recommend treatment, or provide a "
                "medication dosage. Please contact a qualified clinician or pharmacist."
            )
        elif mode == "insufficient_context" or not sources:
            text = (
                "I do not have enough verified hospital information to answer that. "
                "Please contact the appropriate hospital staff."
            )
        else:
            first = sources[0]
            answer = source_answer(str(first["text"]))
            text = f"{answer} [{first['citation']}]"
        citations = sorted(set(CITATION_PATTERN.findall(text)))
        latency = (time.perf_counter() - start) * 1000
        return LLMResponse(
            prompt_id=str(bundle["prompt_id"]), provider=self.name,
            model=config.model, mode=mode, text=text, citations=citations,
            finish_reason="stop", latency_ms=round(latency, 3),
            input_tokens=int(bundle.get("estimated_prompt_tokens", 0)),
            output_tokens=max(1, (len(text) + 3) // 4), request_id=None,
            safety_labels=sorted(map(str, bundle.get("safety_labels", []))),
        )


def json_request(
    url: str,
    payload: dict[str, Any],
    headers: dict[str, str],
    config: ClientConfig,
) -> tuple[dict[str, Any], dict[str, str]]:
    """POST JSON with bounded retries and sanitized provider errors."""
    body = json.dumps(payload).encode("utf-8")
    request_headers = {"Content-Type": "application/json", **headers}
    for attempt in range(config.retries + 1):
        request = urllib.request.Request(url, data=body, headers=request_headers, method="POST")
        try:
            with urllib.request.urlopen(request, timeout=config.timeout_seconds) as response:
                data = json.loads(response.read().decode("utf-8"))
                return data, dict(response.headers.items())
        except urllib.error.HTTPError as error:
            if error.code in TRANSIENT_STATUS_CODES and attempt < config.retries:
                time.sleep(2 ** attempt)
                continue
            raise RuntimeError(
                f"Provider HTTP {error.code}; request was not completed."
            ) from None
        except (urllib.error.URLError, TimeoutError) as error:
            if attempt < config.retries:
                time.sleep(2 ** attempt)
                continue
            raise RuntimeError(f"Provider connection failed: {type(error).__name__}") from None
    raise RuntimeError("Provider request failed after retries.")


def response_result(
    bundle: dict[str, Any], config: ClientConfig, text: str,
    finish_reason: str, start: float, usage: dict[str, Any] | None = None,
    request_id: str | None = None,
) -> LLMResponse:
    """Normalize provider output into the shared LLM response schema."""
    usage = usage or {}
    return LLMResponse(
        prompt_id=str(bundle["prompt_id"]), provider=config.provider,
        model=config.model, mode=str(bundle["mode"]), text=text.strip(),
        citations=sorted(set(CITATION_PATTERN.findall(text))),
        finish_reason=finish_reason or "stop",
        latency_ms=round((time.perf_counter() - start) * 1000, 3),
        input_tokens=usage.get("input_tokens") or usage.get("prompt_token_count"),
        output_tokens=usage.get("output_tokens") or usage.get("candidates_token_count"),
        request_id=request_id,
        safety_labels=sorted(map(str, bundle.get("safety_labels", []))),
    )


class OpenAIProvider:
    """OpenAI Responses API adapter using the standard library."""
    name = "openai"
    def __init__(self, api_key: str):
        if not api_key: raise ValueError("OPENAI_API_KEY is required.")
        self.api_key = api_key
    def generate(self, bundle: dict[str, Any], config: ClientConfig) -> LLMResponse:
        start = time.perf_counter()
        data, headers = json_request(
            str(config.base_url),
            {"model": config.model, "instructions": bundle["system_prompt"],
             "input": bundle["user_prompt"], "max_output_tokens": config.max_output_tokens},
            {"Authorization": f"Bearer {self.api_key}"}, config,
        )
        text = str(data.get("output_text") or "")
        if not text:
            text = "".join(
                item.get("text", "")
                for output in data.get("output", [])
                for item in output.get("content", [])
                if item.get("type") == "output_text"
            )
        return response_result(bundle, config, text, str(data.get("status", "stop")), start,
                               data.get("usage"), data.get("id") or headers.get("x-request-id"))


class GeminiProvider:
    """Google Gemini generateContent REST adapter."""
    name = "gemini"
    def __init__(self, api_key: str):
        if not api_key: raise ValueError("GEMINI_API_KEY is required.")
        self.api_key = api_key
    def generate(self, bundle: dict[str, Any], config: ClientConfig) -> LLMResponse:
        start = time.perf_counter()
        url = f"{str(config.base_url).rstrip('/')}/models/{config.model}:generateContent"
        data, _ = json_request(url, {
            "system_instruction": {"parts": [{"text": bundle["system_prompt"]}]},
            "contents": [{"role": "user", "parts": [{"text": bundle["user_prompt"]}]}],
            "generationConfig": {"maxOutputTokens": config.max_output_tokens},
        }, {"x-goog-api-key": self.api_key}, config)
        candidate = data.get("candidates", [{}])[0]
        text = "".join(part.get("text", "") for part in candidate.get("content", {}).get("parts", []))
        usage = data.get("usageMetadata", {})
        mapped = {"prompt_token_count": usage.get("promptTokenCount"), "candidates_token_count": usage.get("candidatesTokenCount")}
        return response_result(bundle, config, text, str(candidate.get("finishReason", "stop")), start, mapped)


class AnthropicProvider:
    """Anthropic Messages API adapter."""
    name = "anthropic"
    def __init__(self, api_key: str):
        if not api_key: raise ValueError("ANTHROPIC_API_KEY is required.")
        self.api_key = api_key
    def generate(self, bundle: dict[str, Any], config: ClientConfig) -> LLMResponse:
        start = time.perf_counter()
        data, headers = json_request(str(config.base_url), {
            "model": config.model, "max_tokens": config.max_output_tokens,
            "system": bundle["system_prompt"],
            "messages": [{"role": "user", "content": bundle["user_prompt"]}],
        }, {"x-api-key": self.api_key, "anthropic-version": "2023-06-01"}, config)
        text = "".join(item.get("text", "") for item in data.get("content", []) if item.get("type") == "text")
        usage = data.get("usage", {})
        return response_result(bundle, config, text, str(data.get("stop_reason", "stop")), start,
                               usage, data.get("id") or headers.get("request-id"))


class OllamaProvider:
    """Local Ollama chat adapter."""
    name = "ollama"
    def generate(self, bundle: dict[str, Any], config: ClientConfig) -> LLMResponse:
        start = time.perf_counter()
        data, _ = json_request(str(config.base_url), {
            "model": config.model, "stream": False,
            "messages": [
                {"role": "system", "content": bundle["system_prompt"]},
                {"role": "user", "content": bundle["user_prompt"]},
            ],
            "options": {"num_predict": config.max_output_tokens},
        }, {}, config)
        usage = {"input_tokens": data.get("prompt_eval_count"), "output_tokens": data.get("eval_count")}
        return response_result(bundle, config, str(data.get("message", {}).get("content", "")),
                               str(data.get("done_reason", "stop")), start, usage)


def create_provider(config: ClientConfig, values: dict[str, str]) -> Provider:
    """Construct the configured provider without exposing credentials."""
    if config.provider == "offline": return OfflineProvider()
    if config.provider == "openai": return OpenAIProvider(values.get("OPENAI_API_KEY", ""))
    if config.provider == "gemini": return GeminiProvider(values.get("GEMINI_API_KEY", ""))
    if config.provider == "anthropic": return AnthropicProvider(values.get("ANTHROPIC_API_KEY", ""))
    if config.provider == "ollama": return OllamaProvider()
    raise ValueError(f"Unsupported provider: {config.provider}")


def validate_response(bundle: dict[str, Any], response: LLMResponse) -> None:
    """Validate nonempty output, citation integrity, and safety-mode behavior."""
    if not response.text.strip():
        raise RuntimeError("The provider returned an empty response.")
    allowed = {f"[{source['citation']}]" for source in bundle.get("sources", [])}
    if not set(response.citations).issubset(allowed):
        raise RuntimeError("The response contains an unknown citation.")
    text = response.text.casefold()
    if response.mode == "grounded_answer" and allowed and not response.citations:
        raise RuntimeError("Grounded response is missing a source citation.")
    if response.mode == "emergency" and "emergency" not in text:
        raise RuntimeError("Emergency response is missing emergency routing.")
    if response.mode == "unsafe_medical_advice" and not any(term in text for term in ("cannot", "can't", "qualified clinician", "pharmacist")):
        raise RuntimeError("Unsafe-medical-advice response is missing a refusal.")


def write_json(path: Path, payload: Any) -> None:
    """Write readable UTF-8 JSON."""
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")


def write_audit(path: Path, rows: Sequence[dict[str, Any]]) -> None:
    """Write one audit row per successful generation."""
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]) if rows else [])
        writer.writeheader()
        writer.writerows(rows)


def generate_plots(responses: Sequence[LLMResponse], plots_dir: Path) -> tuple[Path, Path]:
    """Plot response latency and output-length distributions."""
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError as error:
        raise RuntimeError("Install matplotlib to generate LLM plots.") from error
    plots_dir.mkdir(parents=True, exist_ok=True)
    latency_path = plots_dir / "09_llm_latency_by_prompt.png"
    length_path = plots_dir / "09_llm_output_length_distribution.png"
    figure, axis = plt.subplots(figsize=(11, 5))
    axis.bar(range(1, len(responses) + 1), [r.latency_ms for r in responses], color="#4A90A4")
    axis.set_title("LLM Client Latency by Prompt")
    axis.set_xlabel("Prompt number")
    axis.set_ylabel("Latency (ms)")
    figure.tight_layout()
    figure.savefig(latency_path, dpi=160)
    plt.close(figure)
    figure, axis = plt.subplots(figsize=(10, 5))
    axis.hist([len(r.text) for r in responses], bins=10, color="#176B87", edgecolor="white")
    axis.set_title("LLM Output Length Distribution")
    axis.set_xlabel("Response characters")
    axis.set_ylabel("Number of responses")
    figure.tight_layout()
    figure.savefig(length_path, dpi=160)
    plt.close(figure)
    return latency_path, length_path


def run_llm_batch(
    prompts_path: Path, output_dir: Path, config: ClientConfig,
    values: dict[str, str],
) -> BatchResult:
    """Generate, validate, report, and visualize responses for all prompts."""
    bundles = load_prompt_bundles(prompts_path.resolve())
    provider = create_provider(config, values)
    responses: list[LLMResponse] = []
    failures: list[dict[str, Any]] = []
    audit: list[dict[str, Any]] = []
    for bundle in bundles:
        try:
            response = provider.generate(bundle, config)
            validate_response(bundle, response)
            responses.append(response)
            audit.append({
                "prompt_id": response.prompt_id, "provider": response.provider,
                "model": response.model, "mode": response.mode,
                "latency_ms": response.latency_ms,
                "input_tokens": response.input_tokens,
                "output_tokens": response.output_tokens,
                "response_characters": len(response.text),
                "citations": ";".join(response.citations), "status": "created",
            })
        except (ValueError, RuntimeError) as error:
            failures.append({"prompt_id": bundle.get("prompt_id", ""), "error": str(error)})
    output_dir = output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    responses_path = output_dir / "09_llm_responses.json"
    report_path = output_dir / "09_llm_report.json"
    audit_path = output_dir / "09_llm_audit.csv"
    failed_path = output_dir / "09_failed_llm_requests.json"
    write_json(responses_path, [asdict(response) for response in responses])
    write_audit(audit_path, audit)
    write_json(failed_path, failures)
    latency_plot, length_plot = generate_plots(responses, output_dir / "plots")
    latencies = [response.latency_ms for response in responses]
    report = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "prompts_input": str(prompts_path.resolve()),
        "input_prompts": len(bundles), "responses_created": len(responses),
        "failed_responses": len(failures), "provider": config.provider,
        "model": config.model, "configuration": asdict(config),
        "mode_counts": dict(sorted(Counter(r.mode for r in responses).items())),
        "latency_ms": {"minimum": min(latencies), "maximum": max(latencies),
                       "mean": round(mean(latencies), 3), "median": round(median(latencies), 3)},
        "output_files": [responses_path.name, report_path.name, audit_path.name,
                         failed_path.name, f"plots/{latency_plot.name}", f"plots/{length_plot.name}"],
    }
    write_json(report_path, report)
    return BatchResult(responses_path, report_path, audit_path, failed_path,
                       latency_plot, length_plot, len(bundles), len(responses), len(failures))


def build_parser() -> argparse.ArgumentParser:
    """Create the Phase 9 command-line parser."""
    root = default_project_root()
    processed = root / "01_data" / "processed"
    parser = argparse.ArgumentParser(description="Generate responses from Phase 8 prompts.")
    parser.add_argument("--prompts", type=Path, default=processed / "08_prompt_bundles.json")
    parser.add_argument("--output-dir", type=Path, default=processed)
    parser.add_argument("--provider", choices=sorted(SUPPORTED_PROVIDERS))
    return parser


def main() -> None:
    """Run the configured provider for every Phase 8 prompt."""
    args = build_parser().parse_args()
    root = default_project_root()
    values = environment(root)
    config = config_from_environment(values, args.provider)
    result = run_llm_batch(args.prompts, args.output_dir, config, values)
    print("LLM client batch completed successfully.")
    print(f"Provider: {config.provider}")
    print(f"Model: {config.model}")
    print(f"Input prompts: {result.input_prompts}")
    print(f"Responses created: {result.responses_created}")
    print(f"Failed responses: {result.failed_responses}")


if __name__ == "__main__":
    main()
