"""Orchestrate retrieval, prompt construction, and safe answer generation."""

from __future__ import annotations

import argparse
import csv
import importlib.util
import json
import sys
import time
from collections import Counter
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from statistics import mean, median
from typing import Any, Final, Sequence


CHAIN_VERSION: Final = "1.0"


@dataclass(frozen=True)
class RAGChainConfig:
    """Validated settings shared by the end-to-end RAG chain."""

    top_k: int = 3
    candidate_count: int = 8
    vector_weight: float = 0.75
    max_sources: int = 4
    max_context_characters: int = 6000
    minimum_confidence: str = "low"

    def __post_init__(self) -> None:
        if self.top_k < 1:
            raise ValueError("top_k must be positive.")
        if self.candidate_count < self.top_k:
            raise ValueError("candidate_count must be at least top_k.")
        if not 0.0 <= self.vector_weight <= 1.0:
            raise ValueError("vector_weight must be between 0 and 1.")
        if self.max_sources < 1:
            raise ValueError("max_sources must be positive.")
        if self.max_context_characters < 500:
            raise ValueError("max_context_characters must be at least 500.")


@dataclass(frozen=True)
class AnswerSource:
    """Source provenance exposed with a final chatbot answer."""

    citation: str
    chunk_id: str
    source_file: str
    source_type: str
    department: str
    content_category: str
    page_reference: str | None
    score: float


@dataclass(frozen=True)
class StageTimings:
    """Measured latency for each RAG stage and the complete request."""

    retrieval_ms: float
    prompt_ms: float
    generation_ms: float
    total_ms: float


@dataclass(frozen=True)
class RAGAnswer:
    """Stable Phase 10 response contract for the API and user interface."""

    answer_id: str
    chain_version: str
    question: str
    answer: str
    mode: str
    citations: list[str]
    sources: list[AnswerSource]
    retrieval_confidence: str
    safety_labels: list[str]
    provider: str
    model: str
    finish_reason: str
    timings: StageTimings


@dataclass(frozen=True)
class ChainRunResult:
    """Paths and totals generated by one Phase 10 evaluation run."""

    answers_path: Path
    report_path: Path
    audit_path: Path
    failed_path: Path
    latency_plot_path: Path
    mode_plot_path: Path
    input_questions: int
    answers_created: int
    failed_answers: int


def default_project_root() -> Path:
    """Return the project root based on this module's location."""
    return Path(__file__).resolve().parents[1]


def import_module(path: Path, module_name: str) -> Any:
    """Import a numbered project module from an explicit file path."""
    if not path.is_file():
        raise FileNotFoundError(f"Required module does not exist: {path}")
    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Could not create an import specification for {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def load_dependencies(project_root: Path) -> tuple[Any, Any, Any]:
    """Load the Phase 7 retriever, Phase 8 prompt builder, and Phase 9 client."""
    pipeline_dir = project_root / "06_rag_pipeline"
    retriever = import_module(pipeline_dir / "07_retriever.py", "phase7_retriever")
    prompt_builder = import_module(
        pipeline_dir / "08_prompt_template.py", "phase8_prompt_template"
    )
    llm_client = import_module(pipeline_dir / "09_llm_client.py", "phase9_llm_client")
    return retriever, prompt_builder, llm_client


def build_stage_configs(
    config: RAGChainConfig,
    retriever: Any,
    prompt_builder: Any,
) -> tuple[Any, Any]:
    """Translate chain settings into the Phase 7 and Phase 8 configurations."""
    retrieval_config = retriever.RetrieverConfig(
        top_k=config.top_k,
        candidate_count=config.candidate_count,
        vector_weight=config.vector_weight,
    )
    prompt_config = prompt_builder.PromptConfig(
        max_sources=config.max_sources,
        max_context_characters=config.max_context_characters,
        minimum_confidence=config.minimum_confidence,
    )
    return retrieval_config, prompt_config


def source_records(bundle: Any) -> list[AnswerSource]:
    """Convert prompt sources into the public answer provenance schema."""
    return [
        AnswerSource(
            citation=f"[{source.citation}]",
            chunk_id=source.chunk_id,
            source_file=source.source_file,
            source_type=source.source_type,
            department=source.department,
            content_category=source.content_category,
            page_reference=source.page_reference,
            score=source.score,
        )
        for source in bundle.sources
    ]


def validate_chain_answer(answer: RAGAnswer) -> None:
    """Validate answer grounding, provenance, and healthcare safety routing."""
    if not answer.question.strip() or not answer.answer.strip():
        raise RuntimeError("Question and answer must not be empty.")
    source_labels = {source.citation for source in answer.sources}
    if not set(answer.citations).issubset(source_labels):
        raise RuntimeError("Final answer contains an unrecognized citation.")
    if answer.mode == "grounded_answer" and answer.sources and not answer.citations:
        raise RuntimeError("Grounded final answer must cite a source.")
    normalized = answer.answer.casefold()
    if answer.mode == "emergency" and "emergency" not in normalized:
        raise RuntimeError("Emergency final answer is missing emergency routing.")
    if answer.mode == "unsafe_medical_advice" and not any(
        phrase in normalized
        for phrase in ("cannot", "can't", "qualified clinician", "pharmacist")
    ):
        raise RuntimeError("Unsafe medical advice was not refused.")
    timing_values = asdict(answer.timings).values()
    if any(float(value) < 0 for value in timing_values):
        raise RuntimeError("Stage timing must not be negative.")


def answer_question(
    question: str,
    sequence: int,
    index_path: Path,
    prompt_settings: dict[str, str],
    chain_config: RAGChainConfig,
    llm_config: Any,
    environment_values: dict[str, str],
    retriever: Any,
    prompt_builder: Any,
    llm_client: Any,
    embedder: Any,
    vector_store: Any,
    department: str | None = None,
    content_category: str | None = None,
) -> RAGAnswer:
    """Run one question through retrieval, prompt construction, and generation."""
    question = " ".join(question.split())
    if not question:
        raise ValueError("Question must not be empty.")
    retrieval_config, prompt_config = build_stage_configs(
        chain_config, retriever, prompt_builder
    )
    total_start = time.perf_counter()

    retrieval_start = time.perf_counter()
    retrieval_response = retriever.retrieve(
        question=question,
        index_path=index_path,
        config=retrieval_config,
        embedder=embedder,
        vector_store=vector_store,
        department=department,
        content_category=content_category,
    )
    retrieval_ms = (time.perf_counter() - retrieval_start) * 1000

    prompt_start = time.perf_counter()
    prompt_bundle = prompt_builder.build_prompt(
        asdict(retrieval_response), prompt_settings, prompt_config, sequence
    )
    prompt_builder.validate_prompt(prompt_bundle, prompt_config)
    prompt_ms = (time.perf_counter() - prompt_start) * 1000

    generation_start = time.perf_counter()
    provider = llm_client.create_provider(llm_config, environment_values)
    bundle_payload = asdict(prompt_bundle)
    llm_response = provider.generate(bundle_payload, llm_config)
    llm_client.validate_response(bundle_payload, llm_response)
    generation_ms = (time.perf_counter() - generation_start) * 1000

    total_ms = (time.perf_counter() - total_start) * 1000
    answer = RAGAnswer(
        answer_id=f"ANSWER-{sequence:03d}",
        chain_version=CHAIN_VERSION,
        question=question,
        answer=llm_response.text,
        mode=prompt_bundle.mode,
        citations=llm_response.citations,
        sources=source_records(prompt_bundle),
        retrieval_confidence=retrieval_response.confidence,
        safety_labels=sorted(set(retrieval_response.safety_labels)),
        provider=llm_response.provider,
        model=llm_response.model,
        finish_reason=llm_response.finish_reason,
        timings=StageTimings(
            retrieval_ms=round(retrieval_ms, 3),
            prompt_ms=round(prompt_ms, 3),
            generation_ms=round(generation_ms, 3),
            total_ms=round(total_ms, 3),
        ),
    )
    validate_chain_answer(answer)
    return answer


def load_questions(path: Path) -> list[dict[str, str]]:
    """Load the sample questions used for end-to-end chain validation."""
    if not path.is_file():
        raise FileNotFoundError(f"Question file does not exist: {path}")
    with path.open(encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))
    if not rows or "question" not in rows[0]:
        raise ValueError("Question CSV must contain a non-empty question column.")
    return rows


def write_json(path: Path, payload: Any) -> None:
    """Write readable UTF-8 JSON."""
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")


def write_audit(path: Path, rows: Sequence[dict[str, Any]]) -> None:
    """Write one compact audit record per successful chain response."""
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]) if rows else [])
        writer.writeheader()
        writer.writerows(rows)


def generate_plots(answers: Sequence[RAGAnswer], plots_dir: Path) -> tuple[Path, Path]:
    """Plot stage latency and response-mode distribution."""
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError as error:
        raise RuntimeError("Install matplotlib to generate RAG chain plots.") from error

    plots_dir.mkdir(parents=True, exist_ok=True)
    latency_path = plots_dir / "10_rag_stage_latency.png"
    mode_path = plots_dir / "10_rag_answer_modes.png"

    numbers = list(range(1, len(answers) + 1))
    retrieval_values = [answer.timings.retrieval_ms for answer in answers]
    prompt_values = [answer.timings.prompt_ms for answer in answers]
    generation_values = [answer.timings.generation_ms for answer in answers]
    figure, axis = plt.subplots(figsize=(11, 5.5))
    axis.bar(numbers, retrieval_values, label="Retrieval", color="#176B87")
    axis.bar(
        numbers,
        prompt_values,
        bottom=retrieval_values,
        label="Prompt",
        color="#64A7B8",
    )
    bottoms = [r + p for r, p in zip(retrieval_values, prompt_values)]
    axis.bar(
        numbers,
        generation_values,
        bottom=bottoms,
        label="Generation",
        color="#E2A44F",
    )
    axis.set_title("RAG Chain Stage Latency by Question")
    axis.set_xlabel("Question number")
    axis.set_ylabel("Latency (ms)")
    axis.legend()
    axis.grid(axis="y", alpha=0.2)
    figure.tight_layout()
    figure.savefig(latency_path, dpi=160)
    plt.close(figure)

    counts = Counter(answer.mode for answer in answers)
    labels = sorted(counts)
    figure, axis = plt.subplots(figsize=(9, 5))
    bars = axis.bar(labels, [counts[label] for label in labels], color="#24566A")
    axis.set_title("RAG Final Answer Modes")
    axis.set_xlabel("Safety and grounding mode")
    axis.set_ylabel("Number of answers")
    axis.tick_params(axis="x", rotation=15)
    for bar in bars:
        axis.text(
            bar.get_x() + bar.get_width() / 2,
            bar.get_height() + 0.05,
            str(int(bar.get_height())),
            ha="center",
        )
    figure.tight_layout()
    figure.savefig(mode_path, dpi=160)
    plt.close(figure)
    return latency_path, mode_path


def run_chain_evaluation(
    questions_path: Path,
    index_path: Path,
    prompt_config_path: Path,
    output_dir: Path,
    project_root: Path,
    chain_config: RAGChainConfig,
    provider_name: str | None = None,
) -> ChainRunResult:
    """Run the complete chain for every sample question and write artifacts."""
    retriever, prompt_builder, llm_client = load_dependencies(project_root)
    embedder, vector_store = retriever.load_dependencies(project_root)
    prompt_settings = prompt_builder.load_prompt_settings(prompt_config_path.resolve())
    environment_values = llm_client.environment(project_root)
    llm_config = llm_client.config_from_environment(
        environment_values, provider=provider_name
    )
    questions = load_questions(questions_path.resolve())
    answers: list[RAGAnswer] = []
    failures: list[dict[str, Any]] = []
    audit: list[dict[str, Any]] = []

    for sequence, row in enumerate(questions, start=1):
        try:
            answer = answer_question(
                question=row["question"],
                sequence=sequence,
                index_path=index_path.resolve(),
                prompt_settings=prompt_settings,
                chain_config=chain_config,
                llm_config=llm_config,
                environment_values=environment_values,
                retriever=retriever,
                prompt_builder=prompt_builder,
                llm_client=llm_client,
                embedder=embedder,
                vector_store=vector_store,
            )
            answers.append(answer)
            audit.append(
                {
                    "answer_id": answer.answer_id,
                    "mode": answer.mode,
                    "retrieval_confidence": answer.retrieval_confidence,
                    "source_count": len(answer.sources),
                    "citations": ";".join(answer.citations),
                    "provider": answer.provider,
                    "model": answer.model,
                    "retrieval_ms": answer.timings.retrieval_ms,
                    "prompt_ms": answer.timings.prompt_ms,
                    "generation_ms": answer.timings.generation_ms,
                    "total_ms": answer.timings.total_ms,
                    "status": "created",
                }
            )
        except (ValueError, RuntimeError, FileNotFoundError) as error:
            failures.append(
                {
                    "answer_id": f"ANSWER-{sequence:03d}",
                    "stage": "rag_chain",
                    "error": str(error),
                }
            )

    output_dir = output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    answers_path = output_dir / "10_rag_answers.json"
    report_path = output_dir / "10_rag_report.json"
    audit_path = output_dir / "10_rag_audit.csv"
    failed_path = output_dir / "10_failed_rag_answers.json"
    write_json(answers_path, [asdict(answer) for answer in answers])
    write_audit(audit_path, audit)
    write_json(failed_path, failures)
    latency_plot, mode_plot = generate_plots(answers, output_dir / "plots")

    total_latencies = [answer.timings.total_ms for answer in answers]
    report = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "chain_version": CHAIN_VERSION,
        "questions_input": str(questions_path.resolve()),
        "index_input": str(index_path.resolve()),
        "prompt_config_input": str(prompt_config_path.resolve()),
        "input_questions": len(questions),
        "answers_created": len(answers),
        "failed_answers": len(failures),
        "provider": llm_config.provider,
        "model": llm_config.model,
        "mode_counts": dict(sorted(Counter(answer.mode for answer in answers).items())),
        "confidence_counts": dict(
            sorted(Counter(answer.retrieval_confidence for answer in answers).items())
        ),
        "total_latency_ms": {
            "minimum": min(total_latencies) if total_latencies else None,
            "maximum": max(total_latencies) if total_latencies else None,
            "mean": round(mean(total_latencies), 3) if total_latencies else None,
            "median": round(median(total_latencies), 3) if total_latencies else None,
        },
        "configuration": asdict(chain_config),
        "output_files": [
            answers_path.name,
            report_path.name,
            audit_path.name,
            failed_path.name,
            f"plots/{latency_plot.name}",
            f"plots/{mode_plot.name}",
        ],
    }
    write_json(report_path, report)
    return ChainRunResult(
        answers_path=answers_path,
        report_path=report_path,
        audit_path=audit_path,
        failed_path=failed_path,
        latency_plot_path=latency_plot,
        mode_plot_path=mode_plot,
        input_questions=len(questions),
        answers_created=len(answers),
        failed_answers=len(failures),
    )


def build_parser() -> argparse.ArgumentParser:
    """Create the Phase 10 command-line parser."""
    root = default_project_root()
    parser = argparse.ArgumentParser(
        description="Run retrieval, prompting, and generation as one RAG chain."
    )
    parser.add_argument("--question", type=str)
    parser.add_argument(
        "--questions",
        type=Path,
        default=root / "01_data" / "sample_queries" / "test_questions.csv",
    )
    parser.add_argument(
        "--index",
        type=Path,
        default=root / "05_vector_store" / "chroma_db" / "06_vector_index.sqlite3",
    )
    parser.add_argument(
        "--prompt-config",
        type=Path,
        default=root / "02_config" / "prompt_config.yaml",
    )
    parser.add_argument(
        "--output-dir", type=Path, default=root / "01_data" / "processed"
    )
    parser.add_argument("--provider", type=str)
    parser.add_argument("--top-k", type=int, default=3)
    return parser


def main() -> None:
    """Run one RAG question or the complete Phase 10 evaluation."""
    args = build_parser().parse_args()
    root = default_project_root()
    chain_config = RAGChainConfig(top_k=args.top_k)
    if args.question:
        retriever, prompt_builder, llm_client = load_dependencies(root)
        embedder, vector_store = retriever.load_dependencies(root)
        settings = prompt_builder.load_prompt_settings(args.prompt_config)
        values = llm_client.environment(root)
        llm_config = llm_client.config_from_environment(values, args.provider)
        answer = answer_question(
            args.question,
            1,
            args.index,
            settings,
            chain_config,
            llm_config,
            values,
            retriever,
            prompt_builder,
            llm_client,
            embedder,
            vector_store,
        )
        print(json.dumps(asdict(answer), indent=2, ensure_ascii=False))
        return
    result = run_chain_evaluation(
        args.questions,
        args.index,
        args.prompt_config,
        args.output_dir,
        root,
        chain_config,
        args.provider,
    )
    print("RAG chain evaluation completed successfully.")
    print(f"Input questions: {result.input_questions}")
    print(f"Answers created: {result.answers_created}")
    print(f"Failed answers: {result.failed_answers}")


if __name__ == "__main__":
    main()
