"""Render the patient-facing Streamlit chat interface."""

from __future__ import annotations

import argparse
import csv
import importlib.util
import json
import os
import sys
from collections import Counter
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from statistics import mean, median
from typing import Any, Final, Mapping, Sequence


APP_VERSION: Final = "1.0"
DEFAULT_SAMPLE_QUESTIONS: Final = (
    "How can I book an appointment?",
    "Where is the cardiology department?",
    "I have severe chest pain. What is wrong with me?",
)


@dataclass(frozen=True)
class StreamlitUIConfig:
    """User-interface configuration independent of Streamlit runtime state."""

    app_title: str = "Hospital Patient Helpdesk Chatbot"
    page_icon: str = "H"
    provider: str = "offline"
    max_visible_sources: int = 4
    enable_feedback_buttons: bool = True

    def __post_init__(self) -> None:
        if not self.app_title.strip():
            raise ValueError("app_title must not be empty.")
        if self.max_visible_sources < 0:
            raise ValueError("max_visible_sources must not be negative.")
        if not self.provider.strip():
            raise ValueError("provider must not be empty.")


@dataclass(frozen=True)
class ChatTurn:
    """One UI chat turn with the user question and assistant response."""

    turn_id: str
    question: str
    response: dict[str, Any]
    created_at_utc: str


@dataclass(frozen=True)
class UIEvaluationResult:
    """Paths and counts generated by one Streamlit UI evaluation."""

    transcript_path: Path
    report_path: Path
    audit_path: Path
    failed_path: Path
    mode_plot_path: Path
    safety_plot_path: Path
    input_questions: int
    transcript_turns: int
    failed_turns: int


def default_project_root() -> Path:
    """Return the project root based on this app module's location."""
    return Path(__file__).resolve().parents[1]


def import_module(path: Path, module_name: str) -> Any:
    """Import a numbered project module by explicit file path."""
    if not path.is_file():
        raise FileNotFoundError(f"Required module does not exist: {path}")
    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Could not import module: {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def load_api_module(project_root: Path) -> Any:
    """Load the Phase 12 backend service used by the Streamlit UI."""
    return import_module(
        project_root / "07_backend" / "12_api_main.py",
        "phase12_api_main_streamlit",
    )


def normalize_question(question: str) -> str:
    """Normalize the user's visible question before service validation."""
    return " ".join(str(question).split())


def source_badges(sources: Sequence[Mapping[str, Any]], limit: int = 4) -> list[str]:
    """Return compact source labels for display below an answer."""
    badges: list[str] = []
    for source in sources[:limit]:
        citation = str(source.get("citation", ""))
        source_file = str(source.get("source_file", "unknown source"))
        department = str(source.get("department") or "General")
        score = source.get("score")
        score_text = f", score {float(score):.3f}" if isinstance(score, (int, float)) else ""
        badges.append(f"{citation} {source_file} ({department}{score_text})")
    return badges


def safety_banner(response: Mapping[str, Any]) -> str:
    """Return the patient-facing safety status line for one response."""
    action = str(response.get("guardrail_action", "pass"))
    risk = str(response.get("risk_level", "low"))
    if action == "pass":
        return "Safety check passed. The answer is grounded in hospital information."
    if risk == "critical":
        return "Emergency safety route applied. Follow the emergency instruction immediately."
    if action == "override":
        return "Safety override applied. Medical diagnosis or dosage guidance was not provided."
    if action == "block":
        return "Safety block applied. The request could not be answered safely."
    if action == "redact":
        return "Sensitive information was redacted before display."
    return "Safety review completed."


def response_to_markdown(response: Mapping[str, Any], max_sources: int = 4) -> str:
    """Render a response into markdown used by Streamlit and the notebook."""
    lines = [
        str(response.get("answer", "")).strip(),
        "",
        f"**Confidence:** {response.get('retrieval_confidence', 'unknown')}",
        f"**Safety:** {safety_banner(response)}",
    ]
    badges = source_badges(response.get("sources", []), max_sources)
    if badges:
        lines.extend(["", "**Sources:**"])
        lines.extend(f"- {badge}" for badge in badges)
    rules = response.get("triggered_rules", [])
    if rules:
        lines.extend(["", "**Triggered safety rules:** " + ", ".join(map(str, rules))])
    return "\n".join(lines)


def transcript_rows(turns: Sequence[ChatTurn]) -> list[dict[str, Any]]:
    """Flatten chat turns for CSV audit and notebook display."""
    rows: list[dict[str, Any]] = []
    for turn in turns:
        response = turn.response
        rows.append({
            "turn_id": turn.turn_id,
            "created_at_utc": turn.created_at_utc,
            "question": turn.question,
            "request_id": response.get("request_id", ""),
            "mode": response.get("mode", ""),
            "retrieval_confidence": response.get("retrieval_confidence", ""),
            "safety_flag": response.get("safety_flag", False),
            "guardrail_action": response.get("guardrail_action", ""),
            "risk_level": response.get("risk_level", ""),
            "citation_count": len(response.get("citations", [])),
            "source_count": len(response.get("sources", [])),
            "latency_ms": response.get("latency_ms", 0),
        })
    return rows


def create_chat_service(project_root: Path, config: StreamlitUIConfig) -> Any:
    """Create the Phase 12 chat service used by the UI."""
    api_main = load_api_module(project_root)
    return api_main.ChatService(
        project_root,
        api_main.ApiConfig(provider=config.provider),
    )


def ask_service(service: Any, question: str) -> dict[str, Any]:
    """Submit one normalized question to the backend service."""
    api_main = sys.modules.get("phase12_api_main_streamlit")
    if api_main is None:
        api_main = load_api_module(default_project_root())
    request = api_main.ChatRequest.from_mapping({"question": normalize_question(question)})
    return service.chat(request)


def write_json(path: Path, payload: Any) -> None:
    """Write readable UTF-8 JSON."""
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")


def write_audit(path: Path, rows: Sequence[dict[str, Any]]) -> None:
    """Write one transcript/audit row per UI chat turn."""
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]) if rows else [])
        writer.writeheader()
        writer.writerows(rows)


def generate_plots(turns: Sequence[ChatTurn], plots_dir: Path) -> tuple[Path, Path]:
    """Plot response modes and safety actions visible in the UI transcript."""
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError as error:
        raise RuntimeError("Install matplotlib to generate Streamlit UI plots.") from error
    plots_dir.mkdir(parents=True, exist_ok=True)
    mode_path = plots_dir / "15_streamlit_response_modes.png"
    safety_path = plots_dir / "15_streamlit_safety_actions.png"

    modes = Counter(turn.response.get("mode", "unknown") for turn in turns)
    labels = sorted(modes)
    figure, axis = plt.subplots(figsize=(9, 5))
    bars = axis.bar(labels, [modes[label] for label in labels], color="#176B87")
    axis.set_title("Streamlit UI Response Modes")
    axis.set_xlabel("Mode")
    axis.set_ylabel("Number of turns")
    axis.tick_params(axis="x", rotation=15)
    for bar in bars:
        axis.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.03, str(int(bar.get_height())), ha="center")
    figure.tight_layout()
    figure.savefig(mode_path, dpi=160)
    plt.close(figure)

    actions = Counter(turn.response.get("guardrail_action", "unknown") for turn in turns)
    labels = sorted(actions)
    figure, axis = plt.subplots(figsize=(8, 5))
    bars = axis.bar(labels, [actions[label] for label in labels], color="#E2A44F")
    axis.set_title("Streamlit UI Safety Actions")
    axis.set_xlabel("Guardrail action")
    axis.set_ylabel("Number of turns")
    for bar in bars:
        axis.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.03, str(int(bar.get_height())), ha="center")
    figure.tight_layout()
    figure.savefig(safety_path, dpi=160)
    plt.close(figure)
    return mode_path, safety_path


def run_ui_evaluation(
    project_root: Path,
    output_dir: Path,
    questions: Sequence[str] = DEFAULT_SAMPLE_QUESTIONS,
    config: StreamlitUIConfig | None = None,
) -> UIEvaluationResult:
    """Run a deterministic sample chat session and write Phase 15 artifacts."""
    config = config or StreamlitUIConfig()
    service = create_chat_service(project_root, config)
    turns: list[ChatTurn] = []
    failures: list[dict[str, str]] = []
    for number, question in enumerate(questions, start=1):
        try:
            response = ask_service(service, question)
            turns.append(ChatTurn(
                turn_id=f"TURN-{number:03d}",
                question=normalize_question(question),
                response=response,
                created_at_utc=datetime.now(timezone.utc).isoformat(),
            ))
        except (ValueError, RuntimeError, FileNotFoundError) as error:
            failures.append({"turn_id": f"TURN-{number:03d}", "error": type(error).__name__})

    output_dir = output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    transcript_path = output_dir / "15_streamlit_transcript.json"
    report_path = output_dir / "15_streamlit_session_report.json"
    audit_path = output_dir / "15_streamlit_ui_audit.csv"
    failed_path = output_dir / "15_failed_streamlit_turns.json"
    write_json(transcript_path, [asdict(turn) for turn in turns])
    write_audit(audit_path, transcript_rows(turns))
    write_json(failed_path, failures)
    mode_plot, safety_plot = generate_plots(turns, output_dir / "plots")

    latencies = [float(turn.response.get("latency_ms", 0)) for turn in turns]
    report = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "app_version": APP_VERSION,
        "input_questions": len(questions),
        "transcript_turns": len(turns),
        "failed_turns": len(failures),
        "streamlit_available": importlib.util.find_spec("streamlit") is not None,
        "configuration": asdict(config),
        "mode_counts": dict(sorted(Counter(turn.response.get("mode", "unknown") for turn in turns).items())),
        "safety_action_counts": dict(sorted(Counter(turn.response.get("guardrail_action", "unknown") for turn in turns).items())),
        "latency_ms": {
            "minimum": min(latencies) if latencies else None,
            "maximum": max(latencies) if latencies else None,
            "mean": round(mean(latencies), 3) if latencies else None,
            "median": round(median(latencies), 3) if latencies else None,
        },
        "output_files": [
            transcript_path.name,
            report_path.name,
            audit_path.name,
            failed_path.name,
            f"plots/{mode_plot.name}",
            f"plots/{safety_plot.name}",
        ],
    }
    write_json(report_path, report)
    return UIEvaluationResult(
        transcript_path=transcript_path,
        report_path=report_path,
        audit_path=audit_path,
        failed_path=failed_path,
        mode_plot_path=mode_plot,
        safety_plot_path=safety_plot,
        input_questions=len(questions),
        transcript_turns=len(turns),
        failed_turns=len(failures),
    )


def running_in_streamlit() -> bool:
    """Return whether the script is currently executed by Streamlit."""
    if "streamlit" not in sys.modules and not os.environ.get("STREAMLIT_SERVER_PORT"):
        return False
    try:
        from streamlit.runtime.scriptrunner import get_script_run_ctx
    except Exception:
        return False
    return get_script_run_ctx() is not None


def render_streamlit_app(project_root: Path | None = None, config: StreamlitUIConfig | None = None) -> None:
    """Render the patient-facing Streamlit chat interface."""
    try:
        import streamlit as st
    except ModuleNotFoundError as error:
        raise RuntimeError("Streamlit is not installed. Install requirements.txt to run the UI.") from error

    project_root = (project_root or default_project_root()).resolve()
    config = config or StreamlitUIConfig()
    logo_path = project_root / "08_app" / "assets" / "hospital_logo.png"

    st.set_page_config(page_title=config.app_title, page_icon=config.page_icon, layout="centered")
    columns = st.columns([1, 5])
    if logo_path.is_file():
        columns[0].image(str(logo_path), use_container_width=True)
    columns[1].title(config.app_title)
    st.caption("Hospital information assistant. Not for emergencies, diagnosis, or medication dosage advice.")
    st.warning("For emergencies, contact local emergency services immediately or go to the nearest emergency department.")

    if "chat_service" not in st.session_state:
        st.session_state.chat_service = create_chat_service(project_root, config)
    if "turns" not in st.session_state:
        st.session_state.turns = []

    with st.sidebar:
        st.header("Example Questions")
        for question in DEFAULT_SAMPLE_QUESTIONS:
            if st.button(question, key=f"example-{question}"):
                st.session_state.pending_question = question
        if st.button("Clear conversation"):
            st.session_state.turns = []
            st.session_state.pop("pending_question", None)
        st.markdown("### Safety")
        st.write("Answers are grounded in approved hospital information and checked by final guardrails.")

    for turn in st.session_state.turns:
        with st.chat_message("user"):
            st.write(turn.question)
        with st.chat_message("assistant"):
            st.markdown(response_to_markdown(turn.response, config.max_visible_sources))
            if config.enable_feedback_buttons:
                st.feedback("thumbs", key=f"feedback-{turn.turn_id}")

    prompt = st.chat_input("Ask a hospital helpdesk question")
    pending = st.session_state.pop("pending_question", None)
    question = pending or prompt
    if question:
        normalized = normalize_question(question)
        with st.chat_message("user"):
            st.write(normalized)
        with st.chat_message("assistant"):
            with st.spinner("Checking hospital information and safety rules..."):
                response = ask_service(st.session_state.chat_service, normalized)
            turn = ChatTurn(
                turn_id=f"TURN-{len(st.session_state.turns) + 1:03d}",
                question=normalized,
                response=response,
                created_at_utc=datetime.now(timezone.utc).isoformat(),
            )
            st.session_state.turns.append(turn)
            st.markdown(response_to_markdown(response, config.max_visible_sources))
            if config.enable_feedback_buttons:
                st.feedback("thumbs", key=f"feedback-{turn.turn_id}")

    if st.session_state.turns:
        rows = transcript_rows(st.session_state.turns)
        st.download_button(
            "Download conversation audit JSON",
            data=json.dumps(rows, indent=2),
            file_name="15_streamlit_conversation_audit.json",
            mime="application/json",
        )


def build_parser() -> argparse.ArgumentParser:
    """Create the Phase 15 command-line parser."""
    root = default_project_root()
    parser = argparse.ArgumentParser(description="Run Streamlit UI evaluation artifacts.")
    parser.add_argument("--output-dir", type=Path, default=root / "01_data" / "processed")
    parser.add_argument("--provider", default="offline")
    return parser


def main() -> None:
    """Render Streamlit when hosted, otherwise generate UI evaluation artifacts."""
    args = build_parser().parse_args()
    root = default_project_root()
    config = StreamlitUIConfig(provider=args.provider)
    if running_in_streamlit():
        render_streamlit_app(root, config)
        return
    result = run_ui_evaluation(root, args.output_dir, config=config)
    print("Streamlit UI evaluation completed successfully.")
    print(f"Input questions: {result.input_questions}")
    print(f"Transcript turns: {result.transcript_turns}")
    print(f"Failed turns: {result.failed_turns}")


if __name__ == "__main__":
    main()
