"""Expose the guarded hospital helpdesk RAG workflow through FastAPI."""

from __future__ import annotations

import argparse
import csv
import importlib.util
import json
import sys
import threading
import time
import uuid
from collections import Counter
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from statistics import mean, median
from typing import Any, Final, Mapping, Sequence


API_VERSION: Final = "1.0"
MAX_QUESTION_CHARACTERS: Final = 1000


@dataclass(frozen=True)
class ApiConfig:
    """Validated runtime settings for the API and chat service."""

    provider: str = "offline"
    top_k: int = 3
    host: str = "127.0.0.1"
    port: int = 8000

    def __post_init__(self) -> None:
        if not self.provider.strip():
            raise ValueError("provider must not be empty.")
        if self.top_k < 1:
            raise ValueError("top_k must be positive.")
        if not self.host.strip():
            raise ValueError("host must not be empty.")
        if not 1 <= self.port <= 65535:
            raise ValueError("port must be between 1 and 65535.")


@dataclass(frozen=True)
class ChatRequest:
    """Framework-independent request passed to the chat service."""

    question: str
    department: str | None = None
    content_category: str | None = None

    @classmethod
    def from_mapping(cls, payload: Mapping[str, Any]) -> "ChatRequest":
        """Normalize and validate a request without retaining unknown fields."""
        question = " ".join(str(payload.get("question", "")).split())
        if len(question) < 2:
            raise ValueError("question must contain at least 2 characters.")
        if len(question) > MAX_QUESTION_CHARACTERS:
            raise ValueError(
                f"question must not exceed {MAX_QUESTION_CHARACTERS} characters."
            )

        def optional_text(name: str, maximum: int = 100) -> str | None:
            value = payload.get(name)
            if value is None:
                return None
            normalized = " ".join(str(value).split())
            if not normalized:
                return None
            if len(normalized) > maximum:
                raise ValueError(f"{name} must not exceed {maximum} characters.")
            return normalized

        return cls(
            question=question,
            department=optional_text("department"),
            content_category=optional_text("content_category"),
        )


@dataclass(frozen=True)
class ApiEvaluationResult:
    """Paths and counts generated by the Phase 12 API evaluation."""

    responses_path: Path
    report_path: Path
    audit_path: Path
    failed_path: Path
    latency_plot_path: Path
    safety_plot_path: Path
    requests_input: int
    responses_created: int
    failed_requests: int


def default_project_root() -> Path:
    """Return the project root based on this backend module's location."""
    return Path(__file__).resolve().parents[1]


def import_module(path: Path, module_name: str) -> Any:
    """Import a numbered project module from an explicit file path."""
    if not path.is_file():
        raise FileNotFoundError(f"Required module does not exist: {path}")
    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Could not import module: {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def load_pipeline_modules(project_root: Path) -> tuple[Any, Any]:
    """Load the Phase 10 chain and Phase 11 guardrail modules."""
    pipeline_dir = project_root / "06_rag_pipeline"
    rag_chain = import_module(pipeline_dir / "10_rag_chain.py", "phase10_rag_chain_api")
    guardrails = import_module(
        pipeline_dir / "11_safety_guardrails.py", "phase11_guardrails_api"
    )
    return rag_chain, guardrails


class ChatService:
    """Long-lived service that owns initialized RAG and safety dependencies."""

    def __init__(self, project_root: Path, config: ApiConfig | None = None) -> None:
        self.project_root = project_root.resolve()
        self.config = config or ApiConfig()
        self.rag_chain, self.guardrails = load_pipeline_modules(self.project_root)
        self.retriever, self.prompt_builder, self.llm_client = (
            self.rag_chain.load_dependencies(self.project_root)
        )
        self.embedder, self.vector_store = self.retriever.load_dependencies(
            self.project_root
        )
        self.index_path = (
            self.project_root
            / "05_vector_store"
            / "chroma_db"
            / "06_vector_index.sqlite3"
        )
        self.prompt_config_path = (
            self.project_root / "02_config" / "prompt_config.yaml"
        )
        self.prompt_settings = self.prompt_builder.load_prompt_settings(
            self.prompt_config_path
        )
        self.environment_values = self.llm_client.environment(self.project_root)
        self.llm_config = self.llm_client.config_from_environment(
            self.environment_values, provider=self.config.provider
        )
        self.chain_config = self.rag_chain.RAGChainConfig(top_k=self.config.top_k)
        self.guardrail_config = self.guardrails.GuardrailConfig()
        self._sequence = 0
        self._sequence_lock = threading.Lock()
        self._validate_readiness()

    def _validate_readiness(self) -> None:
        """Fail startup when critical data contracts are unavailable."""
        if not self.index_path.is_file():
            raise FileNotFoundError(f"Vector index does not exist: {self.index_path}")
        if not self.prompt_config_path.is_file():
            raise FileNotFoundError(
                f"Prompt configuration does not exist: {self.prompt_config_path}"
            )
        self.retriever.load_index_contract(self.index_path)

    def _next_sequence(self) -> int:
        """Return a process-local sequence number safe for concurrent requests."""
        with self._sequence_lock:
            self._sequence += 1
            return self._sequence

    def health(self) -> dict[str, Any]:
        """Return a non-sensitive readiness summary."""
        return {
            "status": "ready",
            "service": "hospital-patient-helpdesk-chatbot",
            "api_version": API_VERSION,
            "provider": self.llm_config.provider,
            "model": self.llm_config.model,
            "index_ready": self.index_path.is_file(),
            "guardrail_version": self.guardrails.GUARDRAIL_VERSION,
            "timestamp_utc": datetime.now(timezone.utc).isoformat(),
        }

    def chat(self, request: ChatRequest) -> dict[str, Any]:
        """Run one validated request through RAG and final safety guardrails."""
        started = time.perf_counter()
        sequence = self._next_sequence()
        rag_answer = self.rag_chain.answer_question(
            question=request.question,
            sequence=sequence,
            index_path=self.index_path,
            prompt_settings=self.prompt_settings,
            chain_config=self.chain_config,
            llm_config=self.llm_config,
            environment_values=self.environment_values,
            retriever=self.retriever,
            prompt_builder=self.prompt_builder,
            llm_client=self.llm_client,
            embedder=self.embedder,
            vector_store=self.vector_store,
            department=request.department,
            content_category=request.content_category,
        )
        guarded = self.guardrails.apply_guardrails(
            asdict(rag_answer), self.guardrail_config
        )
        total_ms = round((time.perf_counter() - started) * 1000, 3)
        return {
            "request_id": f"REQ-{uuid.uuid4().hex[:12].upper()}",
            "answer": guarded.answer,
            "mode": guarded.mode,
            "citations": guarded.citations,
            "sources": guarded.sources,
            "retrieval_confidence": guarded.retrieval_confidence,
            "safety_flag": guarded.safety_flag,
            "guardrail_action": guarded.guardrail_action,
            "risk_level": guarded.risk_level,
            "triggered_rules": guarded.triggered_rules,
            "provider": guarded.provider,
            "model": guarded.model,
            "latency_ms": total_ms,
            "timestamp_utc": datetime.now(timezone.utc).isoformat(),
        }


def create_app(
    project_root: Path | None = None,
    config: ApiConfig | None = None,
) -> Any:
    """Create the FastAPI application with initialized shared service state."""
    try:
        from fastapi import FastAPI, HTTPException
        from pydantic import BaseModel, Field
    except ModuleNotFoundError as error:
        raise RuntimeError(
            "FastAPI dependencies are missing. Install requirements.txt before "
            "creating the web application."
        ) from error

    class ChatRequestModel(BaseModel):
        question: str = Field(min_length=2, max_length=MAX_QUESTION_CHARACTERS)
        department: str | None = Field(default=None, max_length=100)
        content_category: str | None = Field(default=None, max_length=100)

    class SourceModel(BaseModel):
        citation: str
        chunk_id: str | None = None
        source_file: str
        source_type: str | None = None
        department: str | None = None
        content_category: str | None = None
        page_reference: str | None = None
        score: float | None = None

    class ChatResponseModel(BaseModel):
        request_id: str
        answer: str
        mode: str
        citations: list[str]
        sources: list[SourceModel]
        retrieval_confidence: str
        safety_flag: bool
        guardrail_action: str
        risk_level: str
        triggered_rules: list[str]
        provider: str
        model: str
        latency_ms: float
        timestamp_utc: str

    class HealthResponseModel(BaseModel):
        status: str
        service: str
        api_version: str
        provider: str
        model: str
        index_ready: bool
        guardrail_version: str
        timestamp_utc: str

    root = (project_root or default_project_root()).resolve()
    service = ChatService(root, config)
    application = FastAPI(
        title="Hospital Patient Helpdesk Chatbot API",
        description=(
            "Grounded hospital-information responses with deterministic healthcare "
            "safety guardrails. This API does not provide diagnosis or emergency care."
        ),
        version=API_VERSION,
    )
    application.state.chat_service = service

    @application.middleware("http")
    async def add_security_headers(request: Any, call_next: Any) -> Any:
        response = await call_next(request)
        response.headers["Cache-Control"] = "no-store"
        response.headers["X-Content-Type-Options"] = "nosniff"
        response.headers["X-Frame-Options"] = "DENY"
        return response

    @application.get("/", tags=["service"])
    def root_endpoint() -> dict[str, str]:
        return {
            "service": "Hospital Patient Helpdesk Chatbot API",
            "version": API_VERSION,
            "documentation": "/docs",
        }

    @application.get(
        "/health", response_model=HealthResponseModel, tags=["service"]
    )
    def health_endpoint() -> dict[str, Any]:
        return service.health()

    @application.post(
        "/chat", response_model=ChatResponseModel, tags=["chat"]
    )
    def chat_endpoint(payload: ChatRequestModel) -> dict[str, Any]:
        try:
            request = ChatRequest.from_mapping(
                {
                    "question": payload.question,
                    "department": payload.department,
                    "content_category": payload.content_category,
                }
            )
            return service.chat(request)
        except ValueError as error:
            raise HTTPException(status_code=400, detail=str(error)) from None
        except (FileNotFoundError, RuntimeError):
            raise HTTPException(
                status_code=503,
                detail="The chatbot service is temporarily unavailable.",
            ) from None

    return application


def load_sample_requests(path: Path) -> list[ChatRequest]:
    """Load sample questions for API-level service evaluation."""
    if not path.is_file():
        raise FileNotFoundError(f"Sample request file does not exist: {path}")
    with path.open(encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))
    if not rows or "question" not in rows[0]:
        raise ValueError("Sample request CSV must include a question column.")
    return [ChatRequest.from_mapping(row) for row in rows]


def write_json(path: Path, payload: Any) -> None:
    """Write readable UTF-8 JSON."""
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")


def write_audit(path: Path, rows: Sequence[dict[str, Any]]) -> None:
    """Write one privacy-conscious operational row per successful request."""
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]) if rows else [])
        writer.writeheader()
        writer.writerows(rows)


def generate_plots(
    responses: Sequence[dict[str, Any]], plots_dir: Path
) -> tuple[Path, Path]:
    """Plot request latency and final guardrail-action distribution."""
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError as error:
        raise RuntimeError("Install matplotlib to generate API plots.") from error

    plots_dir.mkdir(parents=True, exist_ok=True)
    latency_path = plots_dir / "12_api_request_latency.png"
    safety_path = plots_dir / "12_api_safety_actions.png"

    figure, axis = plt.subplots(figsize=(11, 5))
    axis.bar(
        range(1, len(responses) + 1),
        [response["latency_ms"] for response in responses],
        color="#176B87",
    )
    axis.set_title("API Chat Service Latency by Request")
    axis.set_xlabel("Request number")
    axis.set_ylabel("Latency (ms)")
    axis.grid(axis="y", alpha=0.2)
    figure.tight_layout()
    figure.savefig(latency_path, dpi=160)
    plt.close(figure)

    counts = Counter(response["guardrail_action"] for response in responses)
    labels = sorted(counts)
    figure, axis = plt.subplots(figsize=(8.5, 5))
    bars = axis.bar(labels, [counts[label] for label in labels], color="#E2A44F")
    axis.set_title("API Response Safety Actions")
    axis.set_xlabel("Guardrail action")
    axis.set_ylabel("Number of responses")
    for bar in bars:
        axis.text(
            bar.get_x() + bar.get_width() / 2,
            bar.get_height() + 0.05,
            str(int(bar.get_height())),
            ha="center",
        )
    figure.tight_layout()
    figure.savefig(safety_path, dpi=160)
    plt.close(figure)
    return latency_path, safety_path


def run_api_evaluation(
    questions_path: Path,
    output_dir: Path,
    project_root: Path,
    config: ApiConfig | None = None,
) -> ApiEvaluationResult:
    """Exercise the same service used by `/chat` and write Phase 12 artifacts."""
    service = ChatService(project_root, config)
    requests = load_sample_requests(questions_path.resolve())
    responses: list[dict[str, Any]] = []
    failures: list[dict[str, str]] = []
    audit: list[dict[str, Any]] = []
    for number, request in enumerate(requests, start=1):
        try:
            response = service.chat(request)
            responses.append(response)
            audit.append(
                {
                    "request_number": number,
                    "request_id": response["request_id"],
                    "mode": response["mode"],
                    "retrieval_confidence": response["retrieval_confidence"],
                    "safety_flag": response["safety_flag"],
                    "guardrail_action": response["guardrail_action"],
                    "risk_level": response["risk_level"],
                    "citation_count": len(response["citations"]),
                    "source_count": len(response["sources"]),
                    "latency_ms": response["latency_ms"],
                    "status": "success",
                }
            )
        except (ValueError, RuntimeError, FileNotFoundError) as error:
            failures.append(
                {
                    "request_number": str(number),
                    "error": type(error).__name__,
                }
            )

    output_dir = output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    responses_path = output_dir / "12_api_responses.json"
    report_path = output_dir / "12_api_report.json"
    audit_path = output_dir / "12_api_audit.csv"
    failed_path = output_dir / "12_failed_api_requests.json"
    write_json(responses_path, responses)
    write_audit(audit_path, audit)
    write_json(failed_path, failures)
    latency_plot, safety_plot = generate_plots(responses, output_dir / "plots")

    latencies = [float(response["latency_ms"]) for response in responses]
    report = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "api_version": API_VERSION,
        "questions_input": str(questions_path.resolve()),
        "requests_input": len(requests),
        "responses_created": len(responses),
        "failed_requests": len(failures),
        "provider": service.llm_config.provider,
        "model": service.llm_config.model,
        "mode_counts": dict(sorted(Counter(r["mode"] for r in responses).items())),
        "safety_action_counts": dict(
            sorted(Counter(r["guardrail_action"] for r in responses).items())
        ),
        "latency_ms": {
            "minimum": min(latencies) if latencies else None,
            "maximum": max(latencies) if latencies else None,
            "mean": round(mean(latencies), 3) if latencies else None,
            "median": round(median(latencies), 3) if latencies else None,
        },
        "fastapi_available": importlib.util.find_spec("fastapi") is not None,
        "configuration": asdict(service.config),
        "output_files": [
            responses_path.name,
            report_path.name,
            audit_path.name,
            failed_path.name,
            f"plots/{latency_plot.name}",
            f"plots/{safety_plot.name}",
        ],
    }
    write_json(report_path, report)
    return ApiEvaluationResult(
        responses_path=responses_path,
        report_path=report_path,
        audit_path=audit_path,
        failed_path=failed_path,
        latency_plot_path=latency_plot,
        safety_plot_path=safety_plot,
        requests_input=len(requests),
        responses_created=len(responses),
        failed_requests=len(failures),
    )


def build_parser() -> argparse.ArgumentParser:
    """Create the Phase 12 command-line parser."""
    root = default_project_root()
    parser = argparse.ArgumentParser(description="Run or evaluate the chatbot API.")
    parser.add_argument("--serve", action="store_true")
    parser.add_argument(
        "--questions",
        type=Path,
        default=root / "01_data" / "sample_queries" / "test_questions.csv",
    )
    parser.add_argument(
        "--output-dir", type=Path, default=root / "01_data" / "processed"
    )
    parser.add_argument("--provider", default="offline")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8000)
    return parser


def main() -> None:
    """Start the FastAPI server or run the offline API service evaluation."""
    args = build_parser().parse_args()
    root = default_project_root()
    config = ApiConfig(provider=args.provider, host=args.host, port=args.port)
    if args.serve:
        try:
            import uvicorn
        except ModuleNotFoundError as error:
            raise RuntimeError(
                "Uvicorn is missing. Install requirements.txt before serving the API."
            ) from error
        application = create_app(root, config)
        uvicorn.run(application, host=config.host, port=config.port)
        return

    result = run_api_evaluation(
        args.questions, args.output_dir, root, config
    )
    print("API service evaluation completed successfully.")
    print(f"Input requests: {result.requests_input}")
    print(f"Responses created: {result.responses_created}")
    print(f"Failed requests: {result.failed_requests}")


try:
    app = create_app()
except RuntimeError as startup_error:
    if "FastAPI dependencies are missing" not in str(startup_error):
        raise
    app = None


if __name__ == "__main__":
    main()
