"""Define and validate backend request schemas for the helpdesk API."""

from __future__ import annotations

import argparse
import csv
import importlib.util
import json
import re
from collections import Counter
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from statistics import mean, median
from typing import Any, Final, Mapping, Sequence


SCHEMA_VERSION: Final = "1.0"
MIN_QUESTION_CHARACTERS: Final = 2
MAX_QUESTION_CHARACTERS: Final = 1000
MAX_OPTIONAL_FILTER_CHARACTERS: Final = 100
MAX_SESSION_ID_CHARACTERS: Final = 64
MAX_LANGUAGE_CHARACTERS: Final = 12
MAX_CHANNEL_CHARACTERS: Final = 32
DEFAULT_LANGUAGE: Final = "en"
DEFAULT_CHANNEL: Final = "notebook"
ALLOWED_URGENCY: Final = {"routine", "urgent", "emergency"}
SAFE_TEXT_PATTERN: Final = re.compile(r"^[\w\s.,:;!?@#()\-/+&'\"]+$", re.UNICODE)
SESSION_PATTERN: Final = re.compile(r"^[A-Za-z0-9_.:-]+$")
REQUEST_SENSITIVE_PATTERNS: Final = (
    ("api_key", re.compile(r"\b(?:sk-[A-Za-z0-9_-]{16,}|AIza[A-Za-z0-9_-]{20,})\b")),
    ("ssn", re.compile(r"\b\d{3}-\d{2}-\d{4}\b")),
    ("medical_record_number", re.compile(r"\b(?:MRN|medical record number)\s*[:#-]?\s*[A-Z0-9-]{5,}\b", re.IGNORECASE)),
)


@dataclass(frozen=True)
class RequestValidationConfig:
    """Configurable validation rules for incoming chat requests."""

    min_question_characters: int = MIN_QUESTION_CHARACTERS
    max_question_characters: int = MAX_QUESTION_CHARACTERS
    max_optional_filter_characters: int = MAX_OPTIONAL_FILTER_CHARACTERS
    allow_sensitive_identifiers: bool = False

    def __post_init__(self) -> None:
        if self.min_question_characters < 1:
            raise ValueError("min_question_characters must be positive.")
        if self.max_question_characters < self.min_question_characters:
            raise ValueError("max_question_characters must be >= min_question_characters.")
        if self.max_optional_filter_characters < 1:
            raise ValueError("max_optional_filter_characters must be positive.")


@dataclass(frozen=True)
class ChatRequest:
    """Canonical framework-independent request schema for `/chat`."""

    question: str
    department: str | None = None
    content_category: str | None = None
    session_id: str | None = None
    language: str = DEFAULT_LANGUAGE
    channel: str = DEFAULT_CHANNEL
    urgency: str = "routine"


@dataclass(frozen=True)
class RequestValidationResult:
    """Outcome of validating one raw request payload."""

    request_number: int
    valid: bool
    normalized_request: ChatRequest | None
    errors: list[str]
    warnings: list[str]
    question_characters: int
    rejected_fields: list[str]


@dataclass(frozen=True)
class RequestSchemaRunResult:
    """Paths and counts generated by the Phase 13 validation run."""

    results_path: Path
    report_path: Path
    audit_path: Path
    failed_path: Path
    length_plot_path: Path
    outcomes_plot_path: Path
    input_requests: int
    valid_requests: int
    invalid_requests: int


def default_project_root() -> Path:
    """Return the project root based on this backend module's location."""
    return Path(__file__).resolve().parents[1]


def normalize_whitespace(value: Any) -> str:
    """Convert a value to compact text suitable for schema validation."""
    return " ".join(str(value).split())


def sensitive_labels(text: str) -> list[str]:
    """Return recognized sensitive identifier labels in request text."""
    return [label for label, pattern in REQUEST_SENSITIVE_PATTERNS if pattern.search(text)]


def optional_text(
    payload: Mapping[str, Any],
    field_name: str,
    maximum: int,
    errors: list[str],
) -> str | None:
    """Normalize and validate an optional bounded text field."""
    raw_value = payload.get(field_name)
    if raw_value is None:
        return None
    value = normalize_whitespace(raw_value)
    if not value:
        return None
    if len(value) > maximum:
        errors.append(f"{field_name} must not exceed {maximum} characters.")
        return None
    if not SAFE_TEXT_PATTERN.match(value):
        errors.append(f"{field_name} contains unsupported characters.")
        return None
    return value


def validate_request_payload(
    payload: Mapping[str, Any],
    config: RequestValidationConfig | None = None,
    request_number: int = 1,
) -> RequestValidationResult:
    """Validate one raw request mapping and return a normalized contract."""
    config = config or RequestValidationConfig()
    errors: list[str] = []
    warnings: list[str] = []
    rejected_fields: list[str] = []
    allowed = {"question", "department", "content_category", "session_id", "language", "channel", "urgency"}
    rejected_fields = sorted(set(map(str, payload.keys())) - allowed)
    if rejected_fields:
        warnings.append("Unknown fields were ignored: " + ", ".join(rejected_fields) + ".")

    question = normalize_whitespace(payload.get("question", ""))
    if len(question) < config.min_question_characters:
        errors.append(
            f"question must contain at least {config.min_question_characters} characters."
        )
    if len(question) > config.max_question_characters:
        errors.append(
            f"question must not exceed {config.max_question_characters} characters."
        )
    if question and not SAFE_TEXT_PATTERN.match(question):
        errors.append("question contains unsupported control or markup characters.")
    labels = sensitive_labels(question)
    if labels and not config.allow_sensitive_identifiers:
        errors.append("question contains sensitive identifiers: " + ", ".join(labels) + ".")

    department = optional_text(payload, "department", config.max_optional_filter_characters, errors)
    content_category = optional_text(payload, "content_category", config.max_optional_filter_characters, errors)
    session_id = optional_text(payload, "session_id", MAX_SESSION_ID_CHARACTERS, errors)
    if session_id and not SESSION_PATTERN.match(session_id):
        errors.append("session_id may contain only letters, numbers, dot, underscore, colon, or hyphen.")
        session_id = None
    language = normalize_whitespace(payload.get("language", DEFAULT_LANGUAGE)) or DEFAULT_LANGUAGE
    if len(language) > MAX_LANGUAGE_CHARACTERS or not re.fullmatch(r"[A-Za-z]{2,3}(?:-[A-Za-z]{2})?", language):
        errors.append("language must be a short language code such as en or en-US.")
        language = DEFAULT_LANGUAGE
    channel = normalize_whitespace(payload.get("channel", DEFAULT_CHANNEL)) or DEFAULT_CHANNEL
    if len(channel) > MAX_CHANNEL_CHARACTERS or not re.fullmatch(r"[A-Za-z0-9_-]+", channel):
        errors.append("channel must contain only letters, numbers, underscores, or hyphens.")
        channel = DEFAULT_CHANNEL
    urgency = normalize_whitespace(payload.get("urgency", "routine")).casefold() or "routine"
    if urgency not in ALLOWED_URGENCY:
        errors.append("urgency must be one of routine, urgent, or emergency.")
        urgency = "routine"

    normalized = None if errors else ChatRequest(
        question=question,
        department=department,
        content_category=content_category,
        session_id=session_id,
        language=language,
        channel=channel,
        urgency=urgency,
    )
    return RequestValidationResult(
        request_number=request_number,
        valid=not errors,
        normalized_request=normalized,
        errors=errors,
        warnings=warnings,
        question_characters=len(question),
        rejected_fields=rejected_fields,
    )


def create_pydantic_request_model() -> Any:
    """Create an optional Pydantic model matching the canonical schema."""
    try:
        from pydantic import BaseModel, Field
    except ModuleNotFoundError as error:
        raise RuntimeError(
            "Pydantic is not installed. Install requirements.txt to create the FastAPI request model."
        ) from error

    class ChatRequestModel(BaseModel):
        question: str = Field(min_length=MIN_QUESTION_CHARACTERS, max_length=MAX_QUESTION_CHARACTERS)
        department: str | None = Field(default=None, max_length=MAX_OPTIONAL_FILTER_CHARACTERS)
        content_category: str | None = Field(default=None, max_length=MAX_OPTIONAL_FILTER_CHARACTERS)
        session_id: str | None = Field(default=None, max_length=MAX_SESSION_ID_CHARACTERS)
        language: str = Field(default=DEFAULT_LANGUAGE, max_length=MAX_LANGUAGE_CHARACTERS)
        channel: str = Field(default=DEFAULT_CHANNEL, max_length=MAX_CHANNEL_CHARACTERS)
        urgency: str = Field(default="routine")

        def to_chat_request(self) -> ChatRequest:
            result = validate_request_payload(self.model_dump() if hasattr(self, "model_dump") else self.dict())
            if not result.valid or result.normalized_request is None:
                raise ValueError("Pydantic request did not satisfy canonical validation.")
            return result.normalized_request

    return ChatRequestModel


def load_sample_payloads(path: Path) -> list[dict[str, Any]]:
    """Load sample questions and add adversarial schema cases."""
    if not path.is_file():
        raise FileNotFoundError(f"Sample query file does not exist: {path}")
    with path.open(encoding="utf-8", newline="") as handle:
        rows = [dict(row) for row in csv.DictReader(handle)]
    if not rows or "question" not in rows[0]:
        raise ValueError("Sample query CSV must include a question column.")
    adversarial = [
        {"question": "x", "case": "too_short"},
        {"question": "A" * (MAX_QUESTION_CHARACTERS + 1), "case": "too_long"},
        {"question": "My SSN is 123-45-6789", "case": "sensitive_identifier"},
        {"question": "Where is cardiology?", "department": "D" * 101, "case": "filter_too_long"},
        {"question": "Where is radiology?", "language": "not-a-valid-language-code", "case": "bad_language"},
        {"question": "Where is billing?", "unknown": "ignored", "case": "unknown_field"},
    ]
    return rows + adversarial


def write_json(path: Path, payload: Any) -> None:
    """Write readable UTF-8 JSON."""
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")


def write_audit(path: Path, rows: Sequence[dict[str, Any]]) -> None:
    """Write a privacy-conscious validation audit."""
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]) if rows else [])
        writer.writeheader()
        writer.writerows(rows)


def generate_plots(results: Sequence[RequestValidationResult], plots_dir: Path) -> tuple[Path, Path]:
    """Plot request length distribution and validation outcomes."""
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError as error:
        raise RuntimeError("Install matplotlib to generate request-schema plots.") from error
    plots_dir.mkdir(parents=True, exist_ok=True)
    length_path = plots_dir / "13_question_length_distribution.png"
    outcomes_path = plots_dir / "13_request_validation_outcomes.png"

    figure, axis = plt.subplots(figsize=(10, 5))
    axis.hist([result.question_characters for result in results], bins=10, color="#176B87", edgecolor="white")
    axis.set_title("Request Question Length Distribution")
    axis.set_xlabel("Question characters")
    axis.set_ylabel("Number of requests")
    figure.tight_layout()
    figure.savefig(length_path, dpi=160)
    plt.close(figure)

    counts = Counter("valid" if result.valid else "invalid" for result in results)
    labels = sorted(counts)
    figure, axis = plt.subplots(figsize=(8, 5))
    bars = axis.bar(labels, [counts[label] for label in labels], color="#E2A44F")
    axis.set_title("Request Validation Outcomes")
    axis.set_xlabel("Outcome")
    axis.set_ylabel("Number of requests")
    for bar in bars:
        axis.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.05, str(int(bar.get_height())), ha="center")
    figure.tight_layout()
    figure.savefig(outcomes_path, dpi=160)
    plt.close(figure)
    return length_path, outcomes_path


def run_request_schema_validation(
    sample_queries_path: Path,
    output_dir: Path,
    config: RequestValidationConfig | None = None,
) -> RequestSchemaRunResult:
    """Validate sample and adversarial request payloads and write artifacts."""
    config = config or RequestValidationConfig()
    payloads = load_sample_payloads(sample_queries_path.resolve())
    results = [validate_request_payload(payload, config, number) for number, payload in enumerate(payloads, start=1)]
    output_dir = output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    results_path = output_dir / "13_request_validation_results.json"
    report_path = output_dir / "13_request_schema_report.json"
    audit_path = output_dir / "13_request_schema_audit.csv"
    failed_path = output_dir / "13_failed_request_schema_checks.json"

    serializable = []
    audit = []
    failures = []
    for result in results:
        item = asdict(result)
        serializable.append(item)
        audit.append({
            "request_number": result.request_number,
            "valid": result.valid,
            "question_characters": result.question_characters,
            "error_count": len(result.errors),
            "warning_count": len(result.warnings),
            "rejected_fields": ";".join(result.rejected_fields),
        })
        if not result.valid:
            failures.append({
                "request_number": result.request_number,
                "errors": result.errors,
            })
    write_json(results_path, serializable)
    write_audit(audit_path, audit)
    write_json(failed_path, failures)
    length_plot, outcomes_plot = generate_plots(results, output_dir / "plots")

    lengths = [result.question_characters for result in results]
    valid_count = sum(result.valid for result in results)
    report = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "schema_version": SCHEMA_VERSION,
        "input_file": str(sample_queries_path.resolve()),
        "input_requests": len(results),
        "valid_requests": valid_count,
        "invalid_requests": len(results) - valid_count,
        "pydantic_available": importlib.util.find_spec("pydantic") is not None,
        "configuration": asdict(config),
        "question_characters": {
            "minimum": min(lengths),
            "maximum": max(lengths),
            "mean": round(mean(lengths), 3),
            "median": round(median(lengths), 3),
        },
        "error_counts": dict(sorted(Counter(error for result in results for error in result.errors).items())),
        "output_files": [
            results_path.name,
            report_path.name,
            audit_path.name,
            failed_path.name,
            f"plots/{length_plot.name}",
            f"plots/{outcomes_plot.name}",
        ],
    }
    write_json(report_path, report)
    return RequestSchemaRunResult(
        results_path=results_path,
        report_path=report_path,
        audit_path=audit_path,
        failed_path=failed_path,
        length_plot_path=length_plot,
        outcomes_plot_path=outcomes_plot,
        input_requests=len(results),
        valid_requests=valid_count,
        invalid_requests=len(results) - valid_count,
    )


def build_parser() -> argparse.ArgumentParser:
    """Create the Phase 13 command-line parser."""
    root = default_project_root()
    parser = argparse.ArgumentParser(description="Validate backend request schema examples.")
    parser.add_argument("--sample-queries", type=Path, default=root / "01_data" / "sample_queries" / "test_questions.csv")
    parser.add_argument("--output-dir", type=Path, default=root / "01_data" / "processed")
    return parser


def main() -> None:
    """Run sample and adversarial request-schema validation."""
    args = build_parser().parse_args()
    result = run_request_schema_validation(args.sample_queries, args.output_dir)
    print("Request schema validation completed successfully.")
    print(f"Input requests: {result.input_requests}")
    print(f"Valid requests: {result.valid_requests}")
    print(f"Invalid requests: {result.invalid_requests}")


if __name__ == "__main__":
    main()
