
"""Define and validate chatbot API response schemas."""

from __future__ import annotations

import argparse
import csv
import importlib.util
import json
import re
from collections import Counter
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from statistics import mean, median
from typing import Any, Final, Mapping, Sequence


SCHEMA_VERSION: Final = "1.0"
VALID_MODES: Final = {"grounded_answer", "emergency", "unsafe_medical_advice", "insufficient_context", "security_refusal"}
VALID_CONFIDENCE: Final = {"none", "low", "medium", "high"}
VALID_ACTIONS: Final = {"pass", "override", "block", "redact"}
VALID_RISKS: Final = {"low", "medium", "high", "critical"}
MAX_ANSWER_CHARACTERS: Final = 2500
MAX_SOURCES: Final = 6
CITATION_PATTERN: Final = re.compile(r"^\[S\d+\]$")
REQUEST_ID_PATTERN: Final = re.compile(r"^REQ-[A-F0-9]{12}$")
ISO_TIMESTAMP_PATTERN: Final = re.compile(r"^\d{4}-\d{2}-\d{2}T")


@dataclass(frozen=True)
class ResponseValidationConfig:
    """Configurable validation rules for API responses."""

    max_answer_characters: int = MAX_ANSWER_CHARACTERS
    max_sources: int = MAX_SOURCES
    require_citations_for_grounded_answers: bool = True

    def __post_init__(self) -> None:
        if self.max_answer_characters < 100:
            raise ValueError("max_answer_characters must be at least 100.")
        if self.max_sources < 1:
            raise ValueError("max_sources must be positive.")


@dataclass(frozen=True)
class ResponseSource:
    """One source record returned with a chatbot answer."""

    citation: str
    source_file: str
    chunk_id: str | None = None
    source_type: str | None = None
    department: str | None = None
    content_category: str | None = None
    page_reference: str | None = None
    score: float | None = None


@dataclass(frozen=True)
class ChatResponse:
    """Canonical response schema returned by `/chat`."""

    request_id: str
    answer: str
    mode: str
    citations: list[str]
    sources: list[ResponseSource]
    retrieval_confidence: str
    safety_flag: bool
    guardrail_action: str
    risk_level: str
    triggered_rules: list[str]
    provider: str
    model: str
    latency_ms: float
    timestamp_utc: str


@dataclass(frozen=True)
class ResponseValidationResult:
    """Outcome of validating one raw API response payload."""

    response_number: int
    valid: bool
    normalized_response: ChatResponse | None
    errors: list[str]
    warnings: list[str]
    answer_characters: int
    source_count: int
    citation_count: int


@dataclass(frozen=True)
class ResponseSchemaRunResult:
    """Paths and totals generated by the Phase 14 validation run."""

    results_path: Path
    report_path: Path
    audit_path: Path
    failed_path: Path
    length_plot_path: Path
    outcomes_plot_path: Path
    input_responses: int
    valid_responses: int
    invalid_responses: int


def default_project_root() -> Path:
    """Return the project root based on this backend module's location."""
    return Path(__file__).resolve().parents[1]


def compact_text(value: Any) -> str:
    """Normalize scalar text while preserving safe punctuation."""
    return " ".join(str(value).split())


def validate_source(payload: Mapping[str, Any], number: int) -> tuple[ResponseSource | None, list[str]]:
    """Validate and normalize one source record."""
    errors: list[str] = []
    citation = compact_text(payload.get("citation", ""))
    source_file = compact_text(payload.get("source_file", ""))
    if not CITATION_PATTERN.match(citation):
        errors.append(f"source {number} citation must look like [S1].")
    if not source_file:
        errors.append(f"source {number} source_file is required.")
    score_value = payload.get("score")
    score: float | None = None
    if score_value is not None:
        try:
            score = float(score_value)
        except (TypeError, ValueError):
            errors.append(f"source {number} score must be numeric.")
        else:
            if score < 0:
                errors.append(f"source {number} score must not be negative.")
    if errors:
        return None, errors
    return ResponseSource(
        citation=citation,
        source_file=source_file,
        chunk_id=compact_text(payload.get("chunk_id", "")) or None,
        source_type=compact_text(payload.get("source_type", "")) or None,
        department=compact_text(payload.get("department", "")) or None,
        content_category=compact_text(payload.get("content_category", "")) or None,
        page_reference=compact_text(payload.get("page_reference", "")) or None,
        score=score,
    ), []


def validate_response_payload(
    payload: Mapping[str, Any],
    config: ResponseValidationConfig | None = None,
    response_number: int = 1,
) -> ResponseValidationResult:
    """Validate one raw API response and return a normalized response contract."""
    config = config or ResponseValidationConfig()
    errors: list[str] = []
    warnings: list[str] = []
    required = {
        "request_id", "answer", "mode", "citations", "sources", "retrieval_confidence",
        "safety_flag", "guardrail_action", "risk_level", "triggered_rules", "provider",
        "model", "latency_ms", "timestamp_utc",
    }
    missing = sorted(required - set(payload))
    if missing:
        errors.append("missing required fields: " + ", ".join(missing) + ".")

    request_id = compact_text(payload.get("request_id", ""))
    answer = compact_text(payload.get("answer", ""))
    mode = compact_text(payload.get("mode", ""))
    retrieval_confidence = compact_text(payload.get("retrieval_confidence", ""))
    guardrail_action = compact_text(payload.get("guardrail_action", ""))
    risk_level = compact_text(payload.get("risk_level", ""))
    provider = compact_text(payload.get("provider", ""))
    model = compact_text(payload.get("model", ""))
    timestamp_utc = compact_text(payload.get("timestamp_utc", ""))

    if request_id and not REQUEST_ID_PATTERN.match(request_id):
        warnings.append("request_id does not match the standard generated format.")
    if not answer:
        errors.append("answer must not be empty.")
    if len(answer) > config.max_answer_characters:
        errors.append(f"answer must not exceed {config.max_answer_characters} characters.")
    if mode not in VALID_MODES:
        errors.append("mode is not recognized.")
    if retrieval_confidence not in VALID_CONFIDENCE:
        errors.append("retrieval_confidence is not recognized.")
    if guardrail_action not in VALID_ACTIONS:
        errors.append("guardrail_action is not recognized.")
    if risk_level not in VALID_RISKS:
        errors.append("risk_level is not recognized.")
    if not provider:
        errors.append("provider must not be empty.")
    if not model:
        errors.append("model must not be empty.")

    try:
        latency_ms = float(payload.get("latency_ms", 0))
    except (TypeError, ValueError):
        latency_ms = -1.0
        errors.append("latency_ms must be numeric.")
    if latency_ms < 0:
        errors.append("latency_ms must not be negative.")
    if timestamp_utc and not ISO_TIMESTAMP_PATTERN.match(timestamp_utc):
        warnings.append("timestamp_utc does not look like an ISO-8601 timestamp.")

    citations_raw = payload.get("citations", [])
    sources_raw = payload.get("sources", [])
    triggered_raw = payload.get("triggered_rules", [])
    if not isinstance(citations_raw, list):
        errors.append("citations must be a list.")
        citations: list[str] = []
    else:
        citations = [compact_text(value) for value in citations_raw]
    if not isinstance(sources_raw, list):
        errors.append("sources must be a list.")
        sources_raw = []
    if len(sources_raw) > config.max_sources:
        errors.append(f"sources must not exceed {config.max_sources} records.")
    if not isinstance(triggered_raw, list):
        errors.append("triggered_rules must be a list.")
        triggered_rules: list[str] = []
    else:
        triggered_rules = [compact_text(value) for value in triggered_raw]

    sources: list[ResponseSource] = []
    for index, source_payload in enumerate(sources_raw, start=1):
        if not isinstance(source_payload, Mapping):
            errors.append(f"source {index} must be an object.")
            continue
        source, source_errors = validate_source(source_payload, index)
        errors.extend(source_errors)
        if source is not None:
            sources.append(source)

    for citation in citations:
        if not CITATION_PATTERN.match(citation):
            errors.append(f"citation {citation!r} must look like [S1].")
    source_labels = {source.citation for source in sources}
    unsupported = sorted(set(citations) - source_labels)
    if unsupported:
        errors.append("citations not present in sources: " + ", ".join(unsupported) + ".")
    if config.require_citations_for_grounded_answers and mode == "grounded_answer" and sources and not citations:
        errors.append("grounded answers with sources must include citations.")
    if mode in {"emergency", "unsafe_medical_advice", "security_refusal"} and citations:
        warnings.append("safety/refusal responses usually should not include citations.")
    safety_flag = bool(payload.get("safety_flag", False))
    if guardrail_action == "pass" and safety_flag:
        errors.append("passed responses must not set safety_flag to true.")
    if guardrail_action != "pass" and not safety_flag:
        errors.append("non-pass guardrail actions must set safety_flag to true.")
    if safety_flag and not triggered_rules:
        errors.append("safety_flag responses must include triggered_rules.")
    if not safety_flag and triggered_rules:
        errors.append("non-safety responses must not include triggered_rules.")

    normalized = None if errors else ChatResponse(
        request_id=request_id,
        answer=answer,
        mode=mode,
        citations=citations,
        sources=sources,
        retrieval_confidence=retrieval_confidence,
        safety_flag=safety_flag,
        guardrail_action=guardrail_action,
        risk_level=risk_level,
        triggered_rules=triggered_rules,
        provider=provider,
        model=model,
        latency_ms=round(latency_ms, 3),
        timestamp_utc=timestamp_utc,
    )
    return ResponseValidationResult(
        response_number=response_number,
        valid=not errors,
        normalized_response=normalized,
        errors=errors,
        warnings=warnings,
        answer_characters=len(answer),
        source_count=len(sources_raw) if isinstance(sources_raw, list) else 0,
        citation_count=len(citations),
    )


def create_pydantic_response_model() -> Any:
    """Create optional Pydantic response models matching the canonical schema."""
    try:
        from pydantic import BaseModel, Field
    except ModuleNotFoundError as error:
        raise RuntimeError("Pydantic is not installed. Install requirements.txt to create the FastAPI response model.") from error

    class SourceModel(BaseModel):
        citation: str
        source_file: str
        chunk_id: str | None = None
        source_type: str | None = None
        department: str | None = None
        content_category: str | None = None
        page_reference: str | None = None
        score: float | None = None

    class ChatResponseModel(BaseModel):
        request_id: str
        answer: str = Field(max_length=MAX_ANSWER_CHARACTERS)
        mode: str
        citations: list[str]
        sources: list[SourceModel]
        retrieval_confidence: str
        safety_flag: bool
        guardrail_action: str
        risk_level: str
        triggered_rules: list[str]
        provider: str
        model: str
        latency_ms: float
        timestamp_utc: str

    return ChatResponseModel


def load_api_responses(path: Path) -> list[dict[str, Any]]:
    """Load Phase 12 API responses for schema validation."""
    if not path.is_file():
        raise FileNotFoundError(f"API response file does not exist: {path}")
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, list):
        raise ValueError("API responses must be a JSON list.")
    return payload


def adversarial_responses(base: Mapping[str, Any]) -> list[dict[str, Any]]:
    """Create malformed response examples for validation coverage."""
    def changed(response_id: str, **updates: Any) -> dict[str, Any]:
        payload = dict(base)
        payload.update(updates)
        payload["request_id"] = response_id
        return payload

    return [
        changed("REQ-BAD00000001", answer=""),
        changed("REQ-BAD00000002", citations=["[S9]"]),
        changed("REQ-BAD00000003", mode="grounded_answer", citations=[]),
        changed("REQ-BAD00000004", guardrail_action="override", safety_flag=False, triggered_rules=["GR-003_UNSAFE_MEDICAL_REQUEST"]),
        changed("REQ-BAD00000005", latency_ms=-2),
        changed("REQ-BAD00000006", retrieval_confidence="certain"),
    ]


def write_json(path: Path, payload: Any) -> None:
    """Write readable UTF-8 JSON."""
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")


def write_audit(path: Path, rows: Sequence[dict[str, Any]]) -> None:
    """Write a compact response validation audit."""
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]) if rows else [])
        writer.writeheader()
        writer.writerows(rows)


def generate_plots(results: Sequence[ResponseValidationResult], plots_dir: Path) -> tuple[Path, Path]:
    """Plot answer length distribution and response-validation outcomes."""
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError as error:
        raise RuntimeError("Install matplotlib to generate response-schema plots.") from error
    plots_dir.mkdir(parents=True, exist_ok=True)
    length_path = plots_dir / "14_answer_length_distribution.png"
    outcomes_path = plots_dir / "14_response_validation_outcomes.png"

    figure, axis = plt.subplots(figsize=(10, 5))
    axis.hist([result.answer_characters for result in results], bins=10, color="#176B87", edgecolor="white")
    axis.set_title("Response Answer Length Distribution")
    axis.set_xlabel("Answer characters")
    axis.set_ylabel("Number of responses")
    figure.tight_layout()
    figure.savefig(length_path, dpi=160)
    plt.close(figure)

    counts = Counter("valid" if result.valid else "invalid" for result in results)
    labels = sorted(counts)
    figure, axis = plt.subplots(figsize=(8, 5))
    bars = axis.bar(labels, [counts[label] for label in labels], color="#E2A44F")
    axis.set_title("Response Validation Outcomes")
    axis.set_xlabel("Outcome")
    axis.set_ylabel("Number of responses")
    for bar in bars:
        axis.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.05, str(int(bar.get_height())), ha="center")
    figure.tight_layout()
    figure.savefig(outcomes_path, dpi=160)
    plt.close(figure)
    return length_path, outcomes_path


def run_response_schema_validation(
    api_responses_path: Path,
    output_dir: Path,
    config: ResponseValidationConfig | None = None,
) -> ResponseSchemaRunResult:
    """Validate real and adversarial API responses and write Phase 14 artifacts."""
    config = config or ResponseValidationConfig()
    real_responses = load_api_responses(api_responses_path.resolve())
    payloads = real_responses + (adversarial_responses(real_responses[0]) if real_responses else [])
    results = [validate_response_payload(payload, config, number) for number, payload in enumerate(payloads, start=1)]

    output_dir = output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    results_path = output_dir / "14_response_validation_results.json"
    report_path = output_dir / "14_response_schema_report.json"
    audit_path = output_dir / "14_response_schema_audit.csv"
    failed_path = output_dir / "14_failed_response_schema_checks.json"

    serializable = []
    audit = []
    failures = []
    for result in results:
        serializable.append(asdict(result))
        audit.append({
            "response_number": result.response_number,
            "valid": result.valid,
            "answer_characters": result.answer_characters,
            "source_count": result.source_count,
            "citation_count": result.citation_count,
            "error_count": len(result.errors),
            "warning_count": len(result.warnings),
        })
        if not result.valid:
            failures.append({"response_number": result.response_number, "errors": result.errors})
    write_json(results_path, serializable)
    write_audit(audit_path, audit)
    write_json(failed_path, failures)
    length_plot, outcomes_plot = generate_plots(results, output_dir / "plots")

    lengths = [result.answer_characters for result in results]
    valid_count = sum(result.valid for result in results)
    report = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "schema_version": SCHEMA_VERSION,
        "input_file": str(api_responses_path.resolve()),
        "input_responses": len(results),
        "real_api_responses": len(real_responses),
        "adversarial_responses": len(payloads) - len(real_responses),
        "valid_responses": valid_count,
        "invalid_responses": len(results) - valid_count,
        "pydantic_available": importlib.util.find_spec("pydantic") is not None,
        "configuration": asdict(config),
        "answer_characters": {
            "minimum": min(lengths) if lengths else 0,
            "maximum": max(lengths) if lengths else 0,
            "mean": round(mean(lengths), 3) if lengths else 0,
            "median": round(median(lengths), 3) if lengths else 0,
        },
        "error_counts": dict(sorted(Counter(error for result in results for error in result.errors).items())),
        "output_files": [
            results_path.name,
            report_path.name,
            audit_path.name,
            failed_path.name,
            f"plots/{length_plot.name}",
            f"plots/{outcomes_plot.name}",
        ],
    }
    write_json(report_path, report)
    return ResponseSchemaRunResult(
        results_path=results_path,
        report_path=report_path,
        audit_path=audit_path,
        failed_path=failed_path,
        length_plot_path=length_plot,
        outcomes_plot_path=outcomes_plot,
        input_responses=len(results),
        valid_responses=valid_count,
        invalid_responses=len(results) - valid_count,
    )


def build_parser() -> argparse.ArgumentParser:
    """Create the Phase 14 command-line parser."""
    root = default_project_root()
    parser = argparse.ArgumentParser(description="Validate backend response schema examples.")
    parser.add_argument("--api-responses", type=Path, default=root / "01_data" / "processed" / "12_api_responses.json")
    parser.add_argument("--output-dir", type=Path, default=root / "01_data" / "processed")
    return parser


def main() -> None:
    """Run API response schema validation."""
    args = build_parser().parse_args()
    result = run_response_schema_validation(args.api_responses, args.output_dir)
    print("Response schema validation completed successfully.")
    print(f"Input responses: {result.input_responses}")
    print(f"Valid responses: {result.valid_responses}")
    print(f"Invalid responses: {result.invalid_responses}")


if __name__ == "__main__":
    main()
